name: Publish to PyPI

on:
  push:
    tags: ["v*"]        # v0.1.0 などのタグを切った時だけ

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      id-token: write  # OIDC for trusted publishing

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: 
        python-version: "3.11"

    - name: Build sdist / wheel
      run: |
        pip install build
        python -m build --sdist --wheel --outdir dist

    - name: Publish to TestPyPI (optional)
      if: contains(github.ref, '-rc')   # RC タグならテスト用
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TESTPYPI_API_TOKEN }}

    - name: Publish to PyPI
      if: "!contains(github.ref, '-rc')"   # 本番タグのみ
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true
